version: '3'

services:
  node_app:
    container_name: node_app
    environment:
      TZ: Asia/Bangkok
      USER_NAME: xconnext
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: x.dev
      DB_NAME: app_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30001:3000"
    networks:
      - app_network

  db:
    image: mysql:latest
    restart: always
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: x.dev
      MYSQL_DATABASE: app_db
    networks:
      - app_network

networks:
  app_network:
