version: '3'

services:
  node_app:
    container_name: node_app
    environment:
      TZ: Asia/Bangkok
      USER_NAME: xconnext
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30001:3000"
